# Generated by Django 4.0.4 on 2022-05-23 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInterfaceTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('active', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('title_visible', models.IntegerField()),
                ('logo', models.CharField(max_length=100)),
                ('logo_visible', models.IntegerField()),
                ('css_header_background_color', models.CharField(max_length=10)),
                ('title_color', models.CharField(max_length=10)),
                ('css_header_text_color', models.CharField(max_length=10)),
                ('css_header_link_color', models.CharField(max_length=10)),
                ('css_header_link_hover_color', models.CharField(max_length=10)),
                ('css_module_background_color', models.CharField(max_length=10)),
                ('css_module_text_color', models.CharField(max_length=10)),
                ('css_module_link_color', models.CharField(max_length=10)),
                ('css_module_link_hover_color', models.CharField(max_length=10)),
                ('css_module_rounded_corners', models.IntegerField()),
                ('css_generic_link_color', models.CharField(max_length=10)),
                ('css_generic_link_hover_color', models.CharField(max_length=10)),
                ('css_save_button_background_color', models.CharField(max_length=10)),
                ('css_save_button_background_hover_color', models.CharField(max_length=10)),
                ('css_save_button_text_color', models.CharField(max_length=10)),
                ('css_delete_button_background_color', models.CharField(max_length=10)),
                ('css_delete_button_background_hover_color', models.CharField(max_length=10)),
                ('css_delete_button_text_color', models.CharField(max_length=10)),
                ('list_filter_dropdown', models.IntegerField()),
                ('related_modal_active', models.IntegerField()),
                ('related_modal_background_color', models.CharField(max_length=10)),
                ('related_modal_rounded_corners', models.IntegerField()),
                ('logo_color', models.CharField(max_length=10)),
                ('recent_actions_visible', models.IntegerField()),
                ('favicon', models.CharField(max_length=100)),
                ('related_modal_background_opacity', models.CharField(max_length=5)),
                ('env_name', models.CharField(max_length=50)),
                ('env_visible_in_header', models.IntegerField()),
                ('env_color', models.CharField(max_length=10)),
                ('env_visible_in_favicon', models.IntegerField()),
                ('related_modal_close_button_visible', models.IntegerField()),
                ('language_chooser_active', models.IntegerField()),
                ('language_chooser_display', models.CharField(max_length=10)),
                ('list_filter_sticky', models.IntegerField()),
                ('form_pagination_sticky', models.IntegerField()),
                ('form_submit_sticky', models.IntegerField()),
                ('css_module_background_selected_color', models.CharField(max_length=10)),
                ('css_module_link_selected_color', models.CharField(max_length=10)),
                ('logo_max_height', models.PositiveSmallIntegerField()),
                ('logo_max_width', models.PositiveSmallIntegerField()),
                ('foldable_apps', models.IntegerField()),
            ],
            options={
                'db_table': 'admin_interface_theme',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_venta', models.IntegerField(primary_key=True, serialize=False)),
                ('monto', models.IntegerField()),
                ('forma_pago', models.CharField(max_length=10)),
                ('fecha_venta', models.DateField()),
                ('emitido_en', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'compra',
                'ordering': ['id_venta'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id_comprador', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('correo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'comprador',
                'ordering': ['id_comprador', 'nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContenedorLleno',
            fields=[
                ('id_lleno', models.IntegerField(primary_key=True, serialize=False)),
                ('reservado', models.CharField(max_length=1)),
                ('lleno', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'contenedor_lleno',
                'ordering': ['reservado', 'lleno'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rut_empleado', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=20)),
                ('segundo_nombre', models.CharField(max_length=20)),
                ('primer_apellido', models.CharField(max_length=20)),
                ('segundo_apellido', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=20)),
                ('telefono', models.IntegerField()),
                ('ocupacion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'empleado',
                'ordering': ['primer_nombre', 'ocupacion'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id_horario', models.IntegerField(primary_key=True, serialize=False)),
                ('hora_inicio', models.DateField()),
                ('hora_termino', models.DateField()),
            ],
            options={
                'db_table': 'horarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id_infome', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_informe', models.DateField()),
                ('id_contenedor', models.IntegerField()),
            ],
            options={
                'db_table': 'informe',
                'ordering': ['fecha_informe'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IngresoMaterial',
            fields=[
                ('id_material', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_producto', models.CharField(max_length=1)),
                ('fecha', models.DateTimeField()),
                ('pesos_material', models.IntegerField()),
            ],
            options={
                'db_table': 'ingreso_material',
                'ordering': ['id_material'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventarioContenedores',
            fields=[
                ('id_contenedor', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_contenedor', models.CharField(max_length=1)),
                ('peso', models.IntegerField()),
                ('id_llenado', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Inventario Contenedor',
                'verbose_name_plural': 'Inventario Contenedores',
                'db_table': 'inventario_contenedores',
                'ordering': ['id_contenedor'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LlenadoContenedores',
            fields=[
                ('id_llenado', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_contenedor', models.CharField(max_length=1)),
                ('peso', models.IntegerField()),
                ('estado_contenedor', models.CharField(max_length=10)),
                ('precio', models.IntegerField()),
            ],
            options={
                'db_table': 'llenado_contenedores',
                'ordering': ['tipo_contenedor'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Precios',
            fields=[
                ('id_precio', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_material', models.CharField(max_length=1)),
                ('descripcion', models.CharField(max_length=20)),
                ('precio', models.IntegerField()),
            ],
            options={
                'db_table': 'precios',
                'ordering': ['tipo_material'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('fecha_limite', models.DateField()),
            ],
            options={
                'db_table': 'reserva',
                'ordering': ['fecha'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Retiro',
            fields=[
                ('id_retiro', models.IntegerField(primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=20)),
                ('segundo_nombre', models.CharField(max_length=20)),
                ('primer_apellido', models.CharField(max_length=20)),
                ('segundo_apellido', models.CharField(max_length=20)),
                ('fecha_retiro', models.DateField()),
                ('contacto', models.IntegerField()),
            ],
            options={
                'db_table': 'retiro',
                'ordering': ['primer_apellido'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_venta', models.OneToOneField(db_column='id_venta', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='aapp.compra')),
                ('nombre', models.CharField(max_length=100)),
                ('forma_pago', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'boleta',
                'ordering': ['id_venta', 'nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_venta', models.OneToOneField(db_column='id_venta', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='aapp.compra')),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('giro_industria', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
                ('comuna', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'factura',
                'ordering': ['region', 'comuna'],
                'managed': False,
            },
        ),
    ]
