# Generated by Django 4.0.4 on 2022-05-02 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id_comprador', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('correo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'comprador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contenedor',
            fields=[
                ('id_contenedor', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_contenedor', models.CharField(max_length=1)),
                ('peso', models.IntegerField()),
                ('estado_contenedor', models.CharField(max_length=1)),
                ('precio', models.IntegerField()),
            ],
            options={
                'db_table': 'contenedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContenedorLleno',
            fields=[
                ('id_cont', models.IntegerField(primary_key=True, serialize=False)),
                ('reservado', models.CharField(max_length=1)),
                ('lleno', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'contenedor_lleno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetaAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'deta_asignacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleConte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'detalle_conte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rut_empleado', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=20)),
                ('segundo_nombre', models.CharField(max_length=20)),
                ('primer_apellido', models.CharField(max_length=20)),
                ('segundo_apellido', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=20)),
                ('telefono', models.IntegerField()),
                ('ocupacion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id_infome', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_informe', models.DateField()),
            ],
            options={
                'db_table': 'informe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IngresoMaterial',
            fields=[
                ('id_material', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_producto', models.CharField(max_length=1)),
                ('fecha', models.DateField()),
                ('pesos_material', models.IntegerField()),
            ],
            options={
                'db_table': 'ingreso_material',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Receptor',
            fields=[
                ('rut_receptor', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=20)),
                ('segundo_nombre', models.CharField(max_length=20)),
                ('primer_apellido', models.CharField(max_length=20)),
                ('segundo_apellido', models.CharField(max_length=20)),
                ('turno', models.DateTimeField()),
            ],
            options={
                'db_table': 'receptor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('fecha_limite', models.DateField()),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Retiro',
            fields=[
                ('id_retiro', models.IntegerField(primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=20)),
                ('segundo_nombre', models.CharField(max_length=20)),
                ('primer_apellido', models.CharField(max_length=20)),
                ('segundo_apellido', models.CharField(max_length=20)),
                ('fecha_retiro', models.DateField()),
                ('contacto', models.IntegerField()),
            ],
            options={
                'db_table': 'retiro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.IntegerField(primary_key=True, serialize=False)),
                ('monto', models.IntegerField()),
                ('forma_pago', models.CharField(max_length=10)),
                ('fecha_venta', models.DateField()),
                ('emitido_en', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_venta', models.OneToOneField(db_column='id_venta', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='aapp.venta')),
                ('nombre', models.CharField(max_length=100)),
                ('forma_pago', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'boleta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_venta', models.OneToOneField(db_column='id_venta', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='aapp.venta')),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('giro_industria', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
                ('comuna', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'factura',
                'managed': False,
            },
        ),
    ]
