# Generated by Django 4.0.4 on 2022-06-07 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenedorlleno',
            options={'managed': False, 'ordering': ['reservado', 'precio_total']},
        ),
    ]
