# Generated by Django 4.0.4 on 2022-05-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioContenedores',
            fields=[
                ('id_contenedor', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_contenedor', models.CharField(max_length=1)),
                ('peso', models.IntegerField()),
                ('id_llenado', models.IntegerField()),
            ],
            options={
                'db_table': 'inventario_contenedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LlenadoContenedores',
            fields=[
                ('id_llenado', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_contenedor', models.CharField(max_length=1)),
                ('peso', models.IntegerField()),
                ('estado_contenedor', models.CharField(max_length=10)),
                ('precio', models.IntegerField()),
            ],
            options={
                'db_table': 'llenado_contenedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Precios',
            fields=[
                ('id_precio', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_material', models.CharField(max_length=1)),
                ('descripcion', models.CharField(max_length=20)),
                ('precio', models.IntegerField()),
            ],
            options={
                'db_table': 'precios',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Contenedor',
        ),
        migrations.DeleteModel(
            name='DetalleConte',
        ),
    ]
